export const reservedUsernames = [
  // Ethiopian names
  "Ethiotelecom", "Safari","SafariCom","Teleber","EthioPay","EthioAcademy", "telecom", "deri", "HaileSelassie", "Lucy",
  "Axum", "Lalibela", "AddisAbaba", "Gondar", "Menelik", "Zewditu",
  "Tewodros", "Yohannes", "Derg", "Walia", "Fasilides", "Awash",
  "Simien", "Omo", "Bale", "RasDashen", "ArbaMinch", "BahirDar",
  "Harar", "DireDawa", "Mekelle", "Jigjiga", "Sodore", "Nazret",
  "Hawassa", "DebreZeyit", "Gambella", "Axumite", "Sheba", "Shashamane",
  "BaleGoba", "Lasta", "Adwa", "Zagwe", "Negash", "Adama", "Goba",
  "Semien", "ErtaAle", "Gheralta", "Wenchi", "Borana","oromo" ,"Oromia",
  "Tigray", "Amhara", "Sidama", "Somali", "Gedeo", "Konso", "Gamo",
  "Kaffa", "Afar","Robe","Gada","Sinqe",

  // Other African and global names
  "Mandela", "Nkrumah", "Lumumba", "Kenyatta", "Sankara", "Nyerere",
  "Mugabe", "Selassie", "Kagame", "Biko", "DesmondTutu",

  // Technology-related
  "Google", "Microsoft", "Apple", "Tesla", "Facebook", "Amazon",
  "Netflix", "LinkedIn", "GitHub", "StackOverflow", "Reddit",
  "YouTube", "Spotify", "Twitter",

  // Film and Entertainment
  "Hollywood", "Bollywood", "Nollywood", "Disney", "Marvel", "Pixar",
  "Lucasfilm", "Universal", "WarnerBros", "Paramount", "HBO",

  // Famous organizations
  "UN", "UNICEF", "WHO", "WFP", "UNESCO", "IMF", "WorldBank",
  "AfricanUnion", "RedCross", "DoctorsWithoutBorders", "Greenpeace",

  // Famous nature names
  "Serengeti", "Sahara", "Nile", "VictoriaFalls", "Kilimanjaro",
  "TableMountain", "Madagascar", "Kalahari", "Virunga", "Okavango",

  // Famous animals
  "Lion", "Elephant", "Giraffe", "Cheetah", "Leopard", "Rhino",
  "Hippo", "Gorilla", "Zebra", "Ostrich", "Hyena", "Chimpanzee",

  // Educational and student-related
  "Harvard", "Stanford", "MIT", "Oxford", "Cambridge", "Yale",
  "Princeton", "Columbia", "Berkeley", "Caltech", "UChicago",

  // Attractive and special names
  "Danny", "Tedi", "Aster", "Meron", "Beti", "Birqe", "Nati", "Alem",
  "Sun", "Moon", "Water", "Car", "Plane", "Hello", "Zerihun", "Telahun",
  "Mama", "Daddy", "Jake",

  // Business and other attractive names
  "Success", "Inspire", "Vision", "Innovate", "Pioneer", "Leader",
  "Champion", "Mogul", "Empire", "Network", "Strategy", "Growth",
  "Victory", "Progress", "Nexus", "Synergy", "Venture", "Prosper",
  "Fortune", "Legend", "Triumph", "Zenith", "Courage", "Ambition",
  "Aspire", "Achieve", "Dream", "Impact", "Prime", "Momentum",
  "Radiance", "Prestige", "Velocity", "Fusion", "Eminence", "Merit",
  "Flourish", "Vanguard", "Beacon", "Inception", "Odyssey", "Catalyst",
  "Empower", "Influence", "Summit", "Noble", "Unity", "Echelon",

  // Powerful job titles and fields
  "Doctor", "Police", "Pilot", "Rider", "Captain", "Engineer",
  "SoftwareEngineer", "Software", "Tech", "Data", "Code", "AI", "ML",
  "Finance", "Manager", "Director", "CEO", "CTO", "COO", "CFO", "VP",
  "HR", "Marketing", "Sales", "Consultant", "Analyst", "Designer",
  "Developer", "Strategist", "Architect", "Entrepreneur",

  // Ethiopian company names
  "EthioTelco", "EthioTech", "AddisMills", "HabeshaBrewery", "DashenBank",
  "AwashInsurance", "EthioTrans", "ZemenLogistics", "ECAirways", "EthioSteel",
  "GreenEthio", "BlueNileTech", "RedSunEnergy", "AbyssiniaLaw", "HornAgro",
  "SimbaFoods", "LionTech", "WaliaConsulting", "EthioVision", "EthioLink",
  "GoldStarMining", "DashenPharma", "MarathonGroup", "HabeshaMotors",

  // Ethiopian female names
   "Abrihet", "Adanech", "Adiam", "Aida", "Almaz", "Amarech",
  "Aster", "Azeb", "Banchi", "Bati", "Beti", "Betelhem", "Birqe",
  "Blain", "Brikti", "Chaltu", "Dagmawit", "Desta", "Dinknesh", "Elsabet",
  "Emebet", "Eyerusalem","Eyerus", "Fana", "Fikirte", "Fitawrari", "Freweyni",
  "Gennet", "Girmawit", "Hailemariam", "Haimanot", "Hanna", "Hirut",
  "Ililta", "Jember", "Jitu", "Kidist", "Lensa", "Lidya", "Maki",
  "Martha", "Meklit", "Melat", "Meles", "Mekdes", "Meron", "Meskerem",
  "Metasebia", "Minalush", "Mintesinot", "Misrak", "Mulu", "Nardos",
  "Netsanet",  "Rahel",
  "Rehima",
  "Ruta",
  "Ruth",
  "Rahwa",
  "Reeyot",
  "Rakel",
  "Rebka",
  "Rihana",
  "Rosa",
  "Rahel",
  "Rakeb",
  "Rediet", "Seble", "Selam",
  "Semhar", "Sewasew", "Segenet", "Selamawit", "Selome", "Simegnew",
  "Sinit", "Sitinaf", "Sosina","Tena", "Tewabech", "Tigist", "Tsion", "Tsehay", "Tsedale",
  "Tsedey", "Tsigereda", "Tsion", "Weini", "Worknesh", "Woyzero",
  "Yeshi", "Yeshiemebet", "Yewbdar", "Yodit", "Yohanna", "Yordanos",
  "Zebib", "Zemen", "Zenash", "Zewditu", "Zewdie", "Zinash", "Zinet",
  "Ayenalem", "Berhane", "Birtukan", "Blen", "Dinknesh", "Eshete",
  "Fikir", "Girma", "Hana", "Kalkidan", "Kebedech", "Muluemebet",
  "Muluwork", "Nigist",  "Tigist", "Wubit", "Yalem",

// Ethiopian Male Names
    "Abebe", "Abiy", "Admasu", "Alemayehu","Abraham","Abrish", "Amare", "Asfaw","Asfiti", "Ayalew","Bruk","Belete", "Bekele","Beni","Biniam", "Belay", "Birhanu","Bire","Chala",
    "Dawit","Deva", "Demeke","Dagem","Dagi", "Desta", "Dinku","Dinka", "Dula", "Ephrem","Endale", "Eshetu","Eyuel","Eyasu", "Fasika","Firaol","Fira","Tensae","Fikre", "Fikru", "Gashaw",
    "Getachew", "Getahun", "Getu","Gosa", "Girma", "Habtamu", "Hagos", "Haile", "Hailemariam", "Hailu", "Hassen","Ijera","Jemal",
    "Kassahun", "Kebede", "Kenfe", "Kifle", "Kiros","Kaleab","Lemma", "Legesse", "Mamo", "Mehari", "Melaku", "Meles",
    "Mesfin", "Meskel", "Mulatu", "Mulugeta", "Negash","Naol", "Negussie", "Nigussie", "Nuru","Rediet",
    "Roba",
    "Rakeb",
    "Reta",
    "Rashid",
    "Rezene",
    "Rafael",
    "Rafu",
    "Rahul",
    "Rufael",
    "Rimon",
    "Rasim",
    "Ramzi",
    "Robel","Oliyad", "Sahle",
    "Selassie", "Semere","Samuel","Sami", "Sileshi", "Solomon", "Sufian", "Sultan", "Tadese", "Tadi",
    "Teddy",  "Tamrat", "Tarekegn", "Tadesse", "Tafesse", "Tsegaye", "Teshome",
    "Tesfaye", "Tesfahun", "Tilahun", "Tiruwork", "Tola", "Welde", "Woldemariam", "Woldemichael", "Woldesemayat", "Wondimu",
    "Worku", "Wosene","Yacob", "Yared", "Yesuf", "Yohannes","Yerosan", "Yonatan", "Yonas", "Zeleke", "Zerihun", "Zewdu",


    // Global Religions
    "Christianity",
    "Islam",
    "Hinduism",
    "Buddhism",
    "Judaism",
    "Sikhism",
    "Taoism",
    "Shinto",
    "Bahá'í","Faith",
    "Jainism",
    "Zoroastrianism",
    "Paganism",
    "Wicca",
    "Rastafarianism",
    "Shamanism",
    "Sufism",
    "Spiritism",
    "Humanism",
    "Atheism",
    "Agnosticism",
    "Catholic",
    "Prostentant",
    "muslim",
    "Jewish",
    "Orthodox","Christian",

  // Global company names
  "Google", "Microsoft", "Apple", "Amazon", "Tesla", "Facebook", "Netflix",
  "Twitter", "LinkedIn", "Alphabet", "Samsung", "Sony", "BMW", "Mercedes",
  "Toyota", "Honda", "McDonalds", "CocaCola", "Pepsi", "Nike", "Adidas",
  "Guinness", "Nestle", "Walmart", "Shell", "ExxonMobil", "Chevron",
  "Boeing", "Airbus", "SpaceX", "IBM", "Intel", "Oracle", "Cisco", "Adobe",
  "Salesforce", "WaltDisney", "WarnerBros", "UniversalStudios", "SonyPictures",
  "Fox", "NBCUniversal", "ViacomCBS", "LVMH", "BerkshireHathaway", "JPMorganChase",
  "GoldmanSachs", "MorganStanley", "HSBC", "UBS", "Barclays", "BlackRock",
  "Citigroup", "Accenture", "Deloitte", "KPMG", "PwC", "ErnstYoung", "McKinsey",
  "BainCompany", "BostonConsultingGroup", "Dell", "HP", "Lenovo", "Tencent",
  "Alibaba", "TikTok", "ByteDance", "Huawei", "Xiaomi", "Volkswagen", "Audi",
  "Lufthansa", "BritishAirways", "AirFrance", "DeltaAirLines", "Ryanair", "Emirates",
  "QatarAirways", "SingaporeAirlines", "ANA", "CathayPacific", "KLM", "AirCanada",
  "FedEx", "UPS", "DHL", "Maersk", "UPS", "FedEx",






  // LANGUAGES
  
  "English",
  "Spanish",
  "Mandarin Chinese",
  "Hindi",
  "Arabic",
  "Bengali",
  "Portuguese",
  "Russian",
  "Japanese",
  "Punjabi",
  "German",
  "Javanese",
  "Telugu",
  "Wu (Shanghainese)",
  "Marathi",
  "Turkish",
  "Korean",
  "French",
  "Vietnamese",
  "Tamil",
  "Italian",
  "Urdu",
  "Yue (Cantonese)",
  "Thai",
  "Gujarati",
  "Jin",
  "Southern Min (Hokkien)",
  "Persian",
  "Polish",
  "Pashto",
  "Kannada",
  "Xiang",
  "Malayalam",
  "Sundanese",
  "Hausa",
  "Odia (Oriya)",
  "Burmese",
  "Hakka",
  "Ukrainian",
  "Bhojpuri",
  "Tagalog (Filipino)",
  "Yoruba",
  "Maithili",
  "Uzbek",
  "Sindhi",
  "Amharic",
  "Fula",
  "Romanian",
  "Oromo",
  "Igbo",
  "Azerbaijani",
  "Awadhi",
  "Gan",
  "Cebuano",
  "Dutch",
  "Kurdish",
  "Serbo-Croatian",
  "Malagasy",
  "Saraiki",
  "Nepali",
  "Sinhalese",
  "Chittagonian",
  "Zhuang",
  "Khmer",
  "Turkmen",
  "Assamese",
  "Madurese",
  "Somali",
  "Marwari",
  "Magahi",
  "Haryanvi",
  "Hungarian",
  "Chhattisgarhi",
  "Greek",
  "Chewa",
  "Deccan",
  "Akan",
  "Kazakh",
  "Northern Min",
  "Sylheti",
  "Zulu",
  "Czech",
  "Kinyarwanda",
  "Dhundhari",
  "Haitian Creole",
  "Eastern Min",
  "Ilocano",
  "Quechua",
  "Kirundi",
  "Swedish",
  "Hmong",
  "Shona",
  "Uyghur",
  "Hiligaynon",
  "Mossi",

  //Computer Progrraming languages
 
    "Python",
    "JavaScript",
    "Java",
    "C++",
    "C#",
    "PHP",
    "TypeScript",
    "Swift",
    "Ruby",
    "Go",
    "Kotlin",
    "R",
    "Objective-C",
    "Scala",
    "Perl",
    "Rust",
    "Lua",
    "Haskell",
    "Dart",
    "Julia",
    "MATLAB",
    "Assembly",
    "Visual Basic .NET",
    "F#",
    "Clojure",
    "Erlang",
    "Groovy",
    "Scheme",
    "PowerShell",
    "SQL",
    "HTML",
    "CSS",
    "Bash",
    "Shell",
    "Ada",
    "COBOL",
    "Fortran",
    "Lisp",
    "Prolog",
    "Smalltalk",
    "ABAP",
    "Apex",
    "Delphi",
    "ActionScript",
    "FoxPro",
    "Logo",
    "LabVIEW",
    "MUMPS",
    "PostScript",
    "VBScript",
    "XPath",
    "XSLT",
    "Elixir",
    "Pascal",
    "Scratch",
    "Tcl",
    "OpenCL",
    "CUDA",
    "Verilog",
    "VHDL",
    "SystemVerilog",
    "COOL",
    "Eiffel",
    "Forth",
    "Hack",
    "Ioke",
    "Limbo",
    "MUMPS",
    "Nemerle",
    "Opa",
    "Paradox",
    "Pike",
    "PureScript",
    "Red",
    "Ring",
    "Squirrel",
    "UnrealScript",
    "Vala",
    "WebAssembly",
    "Xojo",
    "Yacc",
    "Z shell",
    "Zeno",
    "Oxygene",
    "Blockly",
    "J",
    "Logtalk",
    "JScript",
    "AngelScript",
    "BETA",
    "AspectJ",
    "BitC",
    "Boo",
    "Clean",
    "Io",
    "Fantom",
    "Limbo",
    "Modula-2",
    "Objective-J",
    "Oz",
    "PL/I",
    "Pike"
,

  // Ethipioan Cities

    "AddisAbaba",
    "DireDawa",
    "Mek'ele",
    "Gondar",
    "Adama",
    "Hawassa",
    "Bahir Dar",
    "Jimma",
    "Bishoftu",
    "Debre Markos",
    "Sodo",
    "Jijiga",
    "Shashamane",
    "Arba Minch",
    "Haramaya",
    "Dessie",
    "Gambela",
    "Nekemte",
    "Asosa",
    "Gurage",
    "Wukro",
    "Woldia",
    
    "Kombolcha",
    "Goba",
    "Dila",
    "Asaita",
    "BuleHora",
    "HagereMaryam",
    "Robe",
    "Werder",
    "Negele",
    "Debre Birhan",
    "Mendi",
    "Dembi Dolo",
    "Shire",
    "ShireIndaSelassie",
    "Bonga",
    "Metu",
    "Gedo",
    "KibreMengist",
    "Bedele",
    "Ginir",
    "Giyon",
    "Fiche",
    "Mojo",
    "Harar",
    "Kombolcha",
    "Sebeta",
    "Dukem",
    "Bati",
    "Gedeb",
    "Wendo",
    "Guder",
    "Agaro",
    "Kofele",
    "Mile",
    "Gimbi",
    "Bichena",
    "Konso",
    "Hosanna",
    "Welenchiti",
    "Yabelo",
    "Aysaita",
    "Gode",
    "Metehara",
    "Abomsa",
    "Motta",
    "Goba",
    "NefasMewcha",
    "Kemise",
    "Mendi",
    "TuluBolo",
    "Makale",
    "Deder",
    "GebreGuracha",
    "Fiche",
    "MizanTeferi",
    "Wolenchiti",
    "Sodo",
    "AlemGena",
    "Bonga",
    "Dangla",
    "YirgaAlem",
    "DebreTabor",
    "DoloBay",
    "Gedo",
    "Guduru",
    "Maji",
    "Dejen",
    "Gimbi",
    "FinoteSelam",
    "Bichena",
    "Shashemene",
    "GebreGuracha",

    // JOBS
      "SoftwareEngineer",
      "Teacher",
      "Nurse",
      "Doctor",
      "Engineer",
      "Accountant",
      "Electrician",
      "Mechanic",
      "Plumber",
      "Chef",
      "GraphicDesigner",
      "WebDeveloper",
      "Lawyer",
      "Architect",
      "PoliceOfficer",
      "Firefighter",
      "Paramedic",
      "Dentist",
      "Veterinarian",
      "Pharmacist",
      "Construction Worker",
      "Carpenter",
      "Waiter","Waitress",
      "Bartender",
      "Salesperson",
      "MarketingManager",
      "HRManager",
      "CustomerServiceRepresentative",
      "FinancialAnalyst",
      "DataAnalyst",
      "ProjectManager",
      "OperationsManager",
      "EventPlanner",
      "RealEstateAgent",
      "InsuranceAgent",
      "SocialWorker",
      "Artist",
      "Musician",
      "Actor","Actress",
      "Writer",
      "Journalist",
      "Photographer",
      "Librarian",
      "Translator",
      "Interpreter",
      "Electrician",
      "Welder",
      "Machinist",
      "QualityAssuranceTester",
      "EnvironmentalScientist",
      "Biologist",
      "Chemist",
      "Physicist",
      "Geologist",
      "Meteorologist",
      "Astronomer",
      "Psychologist",
      "Counselor",
      "Therapist",
      "SocialMediaManager",
      "ContentCreator",
      "SEOSpecialist",
      "UX/UIDesigner",
      "FashionDesigner",
      "InteriorDesigner",
      "FitnessTrainer",
      "YogaInstructor",
      "PersonalTrainer",
      "Coach",
      "Nutritionist",
      "Dietitian",
      "PhysicalTherapist",
      "OccupationalTherapist",
      "SpeechTherapist",
      "Chiropractor",
      "MassageTherapist",
      "LifeCoach",
      "Consultant",
      "FinancialAdvisor",
      "InvestmentBanker",
      "Stockbroker",
      "Entrepreneur",
      "SmallBusinessOwner",
      "CEO",
      "ExecutiveAssistant",
      "Secretary",
      "OfficeManager",
      "Receptionist",
      "AdministrativeAssistant",
      "VirtualAssistant",
      "WarehouseWorker",
      "LogisticsCoordinator",
      "TruckDriver",
      "DeliveryDriver",
      "ForkliftOperator",
      "SecurityGuard",
      "Janitor",
      "Housekeeper",
      "Landscaper",
      "Gardener"
  
  


];
